[build]
  # Directory with the client code
  base = "client/"
  
  # Directory that contains the deploy-ready HTML files and assets
  publish = "build/"
  
  # Build command
  command = "npm run build"

# Redirect all requests to index.html for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
