# Railway + Nixpacks configuration for Business Ideas Backend API
# This deploys the Node.js/Express server from the /server directory

[variables]
    NODE_ENV = "production"

[phases.setup]
    nixPkgs = ["nodejs-18_x"]

[phases.install]
    cmds = [
        "cd server && npm ci --production"
    ]

[phases.build]
    cmds = ["echo 'Backend API build completed - no build step required'"]

[start]
    cmd = "cd server && npm start"
